<?php

namespace Aiki\SubscribeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AutorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorityRepository extends EntityRepository
{
}
